server:
    port: 8280 

    
spring:
    application:
             name: springboot2
             
             
management:
  security:
    enabled: false #关掉安全认证
  port: 8888 #管理端口
  context-path: /monitor #actuator的访问路径             